### ISSUE TITLE
Git is removed in latest version

### ISSUE THREAD

**Issue by zhanghaowx** [emmenko/docker-nodejs-karma#1]
In last commit (06f6529857454f90927ce1a8ebbf598ebdb3aff3), git is removed. Is there any reason for removing it?

**Comment by emmenko** [comment]
Not really, but I can add it again if you think it's useful.

**Comment by emmenko** [comment]
Alright, you can get the new image from `latest` or `0.2.0` tag :)

**Comment by emmenko** [comment]
Also, the image size is much smaller now, `~214MB` ;)

**Comment by zhanghaowx** [comment]
Thanks a lot, that is very helpful!
